stages:
 - deploy
deploy:
  stage: deploy
  script:
    - cd ~/10flats
    - git pull git@gitlab.com:Awakerr/10flats.git
    - docker-compose stop
    - docker-compose up -d --force-recreate
  only:
    - master
  tags:
    - docker