stages:
 - deploy
deploy:
  stage: deploy
  script:
    - cd ~/10flats
    - git pull git@gitlab.com:Awakerr/10flats.git
    - docker-compose stop
    - docker-compose up --build --force-recreate -d
  only:
    - master
  tags:
    - docker