# Generated by Django 2.2 on 2019-05-14 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environment', '0001_initial'),
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='You can find here : \nhttps://alpari.com/ru/beginner/articles/currency-codes/', max_length=4, null=True, verbose_name='Currency code')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'verbose_name': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='DistanceMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(blank=True, null=True, verbose_name='Distance')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duration')),
                ('complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.RealtyComplex', verbose_name='Realty Complex')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='environment.Place', verbose_name='Place, object')),
            ],
            options={
                'verbose_name_plural': 'Places',
                'verbose_name': 'Place',
            },
        ),
    ]
