# Generated by Django 2.2 on 2019-05-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Создан')),
                ('first_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Фамилия')),
                ('telegram_username', models.CharField(blank=True, max_length=80, null=True, verbose_name='Username в Telegram')),
                ('telegram_chat_id', models.IntegerField(blank=True, null=True, verbose_name='ID чата в Telegram')),
                ('telegram_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone в Telegram')),
                ('referral', models.CharField(blank=True, max_length=20, null=True, verbose_name='Откуда пришел')),
            ],
            options={
                'verbose_name_plural': 'Аккаунты пользователей Telegram',
                'verbose_name': 'Аккаунт пользователя Telegram',
            },
        ),
    ]
