# Generated by Django 2.2 on 2019-05-10 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=40, null=True, verbose_name='Info')),
            ],
            options={
                'verbose_name_plural': 'Additional info',
                'verbose_name': 'Additional info',
            },
        ),
        migrations.CreateModel(
            name='EthnicGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=90, null=True, verbose_name='Group')),
            ],
            options={
                'verbose_name_plural': 'Ethnic Groups',
                'verbose_name': 'Ethnic Group',
            },
        ),
        migrations.CreateModel(
            name='HeatingConditioning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=90, null=True, verbose_name='Heating/Conditioning type')),
            ],
            options={
                'verbose_name_plural': 'Heating/Conditioning types',
                'verbose_name': 'Heating/Conditioning type',
            },
        ),
        migrations.CreateModel(
            name='HotWaterSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=90, null=True, verbose_name='Water supply type')),
            ],
            options={
                'verbose_name_plural': 'Hot water supply type',
                'verbose_name': 'Hot water supply type',
            },
        ),
        migrations.CreateModel(
            name='InfoSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=90, null=True, verbose_name='Info source')),
            ],
            options={
                'verbose_name_plural': 'Info sources',
                'verbose_name': 'Info source',
            },
        ),
        migrations.CreateModel(
            name='ManagementCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=90, null=True, verbose_name='Name')),
                ('site_url', models.URLField(blank=True, null=True, verbose_name='Site url')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact phone')),
            ],
            options={
                'verbose_name_plural': 'Management companies',
                'verbose_name': 'Management company',
            },
        ),
        migrations.CreateModel(
            name='ObjectPaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=90, null=True, verbose_name='Payment order')),
            ],
            options={
                'verbose_name_plural': 'Payment orders',
                'verbose_name': 'Payment order',
            },
        ),
        migrations.CreateModel(
            name='PropertyFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Property format')),
            ],
            options={
                'verbose_name_plural': 'Property formats',
                'verbose_name': 'Property formats',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=90, null=True, verbose_name='Property type')),
            ],
            options={
                'verbose_name_plural': 'Property types',
                'verbose_name': 'Property type',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=40, null=True, verbose_name='Region')),
            ],
            options={
                'verbose_name_plural': 'Regions',
                'verbose_name': 'Region',
            },
        ),
        migrations.CreateModel(
            name='WaterSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=90, null=True, verbose_name='Water supply type')),
            ],
            options={
                'verbose_name_plural': 'Water supply types',
                'verbose_name': 'Water supply type',
            },
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=40, null=True, verbose_name='Place type')),
                ('info', models.ManyToManyField(to='properites.AdditionalInfo', verbose_name='Additional info')),
            ],
            options={
                'verbose_name_plural': 'Additional info',
                'verbose_name': 'Additional info',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='City')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properites.Region', verbose_name='Region')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'verbose_name': 'City',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=40, null=True, verbose_name='Area')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properites.City', verbose_name='City')),
            ],
            options={
                'verbose_name_plural': 'Areas',
                'verbose_name': 'Area',
            },
        ),
    ]
