# Generated by Django 2.2 on 2019-05-14 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=90, null=True, verbose_name='Lisainfo')),
            ],
            options={
                'verbose_name_plural': 'Lisainfo',
                'verbose_name': 'Lisainfo',
            },
        ),
        migrations.CreateModel(
            name='CustomDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=90, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Custom Descriptions',
                'verbose_name': 'Custom Description',
            },
        ),
        migrations.CreateModel(
            name='EnergyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_class', models.CharField(blank=True, max_length=90, null=True, verbose_name='Energy class')),
            ],
            options={
                'verbose_name_plural': 'Energy classes',
                'verbose_name': 'Energy class',
            },
        ),
        migrations.CreateModel(
            name='HeatingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=90, null=True, verbose_name='Küte ja ventilatsioon')),
            ],
            options={
                'verbose_name_plural': 'Küte ja ventilatsioon',
                'verbose_name': 'Küte ja ventilatsioon',
            },
        ),
        migrations.CreateModel(
            name='KitchenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=90, null=True, verbose_name='Köök')),
            ],
            options={
                'verbose_name_plural': 'Köök',
                'verbose_name': 'Köök',
            },
        ),
        migrations.CreateModel(
            name='ObjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=90, null=True, verbose_name='Side ja turvalisus')),
            ],
            options={
                'verbose_name_plural': 'Side ja turvalisus',
                'verbose_name': 'Side ja turvalisus',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=40, null=True, verbose_name='Region')),
            ],
            options={
                'verbose_name_plural': 'Regions',
                'verbose_name': 'Region',
            },
        ),
        migrations.CreateModel(
            name='WCInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=90, null=True, verbose_name='Sanruum')),
            ],
            options={
                'verbose_name_plural': 'Sanruum',
                'verbose_name': 'Sanruum',
            },
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=40, null=True, verbose_name='Place type')),
                ('info', models.ManyToManyField(to='properites.AdditionalInfo', verbose_name='Additional info')),
            ],
            options={
                'verbose_name_plural': 'Additional info',
                'verbose_name': 'Additional info',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='City')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properites.Region', verbose_name='Region')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'verbose_name': 'City',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=40, null=True, verbose_name='Area')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properites.City', verbose_name='City')),
            ],
            options={
                'verbose_name_plural': 'Areas',
                'verbose_name': 'Area',
            },
        ),
    ]
