# Generated by Django 2.2 on 2019-05-14 18:36

from django.db import migrations, models
import django.db.models.deletion
import urlshortener.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.SlugField(max_length=10, null=True, verbose_name='Короткий ID')),
                ('description', models.CharField(max_length=80, null=True, verbose_name='Описание')),
                ('basic_url', urlshortener.models.ExtendedUrlField(verbose_name='Общая ссылка')),
                ('pub_date', models.DateTimeField(null=True, verbose_name='Добавлено')),
                ('times_sent', models.IntegerField(default=0, verbose_name='Отправлено раз')),
                ('last_click', models.DateTimeField(null=True, verbose_name='Последний переход')),
                ('count', models.IntegerField(default=0, verbose_name='Количество переходов')),
            ],
            options={
                'verbose_name_plural': 'Короткие ссылки',
                'verbose_name': 'Короткую ссылку',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_time', models.DateTimeField(null=True, verbose_name='Переход')),
                ('user_data', models.TextField(default='[]', null=True, verbose_name='Юзер агент')),
                ('user_ip', models.CharField(default='', max_length=15, null=True, verbose_name='IP адрес')),
                ('short_url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urlshortener.ShortUrl', verbose_name='Короткая ссылка')),
            ],
            options={
                'verbose_name_plural': 'Юзерагенты',
                'verbose_name': 'Юзерагент',
            },
        ),
    ]
